sonar.projectKey=jenkins-nodejs-ci
sonar.projectName=Jenkins NodeJS CI
#sonar.sources=.
#sonar.exclusions=node_modules/**,coverage/**,tests/**
sonar.sourceEncoding=UTF-8
# Exclude heavy directories and lock files from analysis
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, **/*.spec.ts, **/*.test.js, package-lock.json

# If you only want source files scanned
sonar.sources=src