replicaCount: 2

image:
  repository: 171226592813.dkr.ecr.us-east-1.amazonaws.com/jenkins-nodejs-app
  pullPolicy: IfNotPresent
  tag: "31"

service:
  type: ClusterIP
  port: 3000
  metricsPort: 3001

observability:
  serviceMonitor:
    enabled: false
    interval: 15s
    scrapeTimeout: 10s
    additionalLabels:
      release: monitoring

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
    promtail.io/scrape: "true"

containerPort: 3000

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 2
  periodSeconds: 5

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
